server:
  port: 8000
  servlet:
    context-path: /shopme
spring:
  datasource:
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://localhost:3306/shopmedb?allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 361620314298-qtula61gfeiace1ihotica705tlbejpb.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile