version: '3'
services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopmedb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass12345678

    networks:
      - my_network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./ShopmeWebParent/ShopmeBackend
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/shopmedb?allowPublicKeyRetrieval=true
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:

