version: '3'
services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopmedb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass12345678

    networks:
      - my_network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./ShopmeWebParent/ShopmeBackend
    restart: always
    environment:
      - DB_URL=jdbc:mysql://mysql_db:3306/shopmedb?allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql_db
    ports:
      - "8083:8083"
    networks:
      - my_network

  frontend:
    build: ./ShopmeWebParent/ShopmeFrontend
    restart: always
    depends_on:
      - mysql_db
    environment:
      - DB_URL=jdbc:mysql://mysql_db:3306/shopmedb?allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "8000:8000"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:

